POST http://localhost:4000/app/EditProduct/prod6
Content-Type:application/json

{
        "name":"product3",
        "description":"product3",
        "price":5689,
        "curency":"EURO",
        "status":"bought"
}